import { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { fetchQuestion, submitSessionAttempt, type Question } from '../api'
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'

export default function Session() {
  const location = useLocation()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  
  // Retrieve the session block generated by the Dashboard
  const sessionData = location.state?.sessionData
  
  // State for block progression and timing
  const [currentIndex, setCurrentIndex] = useState(0)
  const [timeSpent, setTimeSpent] = useState(0)
  
  // State for current question interactions
  const [selectedOption, setSelectedOption] = useState<number | null>(null)
  const [struckOptions, setStruckOptions] = useState<number[]>([])
  const [attemptResult, setAttemptResult] = useState<any>(null)
  
  // Boot user back to dashboard if they navigate here directly without generating a block
  useEffect(() => {
    if (!sessionData) navigate('/')
  }, [sessionData, navigate])

  // Timer logic for the active question
  useEffect(() => {
    if (attemptResult) return // Stop timer when answer is submitted
    const timer = setInterval(() => setTimeSpent(prev => prev + 1), 1000)
    return () => clearInterval(timer)
  }, [attemptResult, currentIndex])

  const currentQuestionId = sessionData?.question_ids[currentIndex]

  // Fetch the active question
  const { data: question, isLoading } = useQuery({
    queryKey: ['question', currentQuestionId],
    queryFn: () => fetchQuestion(currentQuestionId!),
    enabled: !!currentQuestionId,
    refetchOnWindowFocus: false,
  })

  const sessionTitle = sessionData?.qbank === 'medqa_usmle' 
    ? (question?.exam_type || 'USMLE Practice')
    : (question?.subject ? `MedMCQA • ${question.subject}` : 'MedMCQA • Custom Block');

  // Submit attempt mutation
  const attemptMutation = useMutation({
    mutationFn: (opt: number) => submitSessionAttempt(sessionData.session_id, currentQuestionId!, opt, timeSpent),
    onSuccess: (data) => {
      setAttemptResult(data)
      queryClient.invalidateQueries({ queryKey: ['dashboardStats'] })
    },
  })

  if (!sessionData) return null

  const handleSelectOption = (index: number) => {
    if (!attemptResult) setSelectedOption(index)
  }

  const handleToggleStrike = (e: React.MouseEvent, index: number) => {
    e.preventDefault()
    if (!attemptResult) {
      setStruckOptions(prev => prev.includes(index) ? prev.filter(i => i !== index) : [...prev, index])
    }
  }

  const handleSubmit = () => {
    if (selectedOption !== null) attemptMutation.mutate(selectedOption)
  }

  const handleNext = () => {
    if (currentIndex + 1 >= sessionData.question_ids.length) {
      navigate('/') // Block complete, return to dashboard
    } else {
      // Reset state for the next question in the queue
      setSelectedOption(null)
      setStruckOptions([])
      setAttemptResult(null)
      setTimeSpent(0)
      setCurrentIndex(prev => prev + 1)
    }
  }

  if (isLoading) {
      return (
        <div className="w-full flex items-center justify-center mt-12">
          <Skeleton className="h-[400px] w-full max-w-4xl bg-slate-200 dark:bg-slate-800/50 rounded-2xl" />
        </div>
      )
    }

  const options = question?.options || [question?.opa, question?.opb, question?.opc, question?.opd]

  return (
    <div className="w-full max-w-4xl mx-auto flex flex-col space-y-8 animate-in fade-in duration-500 mt-4">
      
      {/* Session Header */}
      <header className="w-full flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
        <div className="flex items-center space-x-4">
          <div>
            <h1 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">{sessionTitle}</h1>
            <p className="text-xs text-slate-500 dark:text-slate-400">Right-click to strike through</p>
          </div>
        </div>
        
        <div className="flex items-center space-x-3 text-sm">
          <Badge variant="outline" className="px-3 py-1 text-slate-600 dark:text-slate-400 border-slate-300 dark:border-slate-700 bg-transparent">
            {Math.floor(timeSpent / 60)}:{(timeSpent % 60).toString().padStart(2, '0')}
          </Badge>
          <Badge className="px-3 py-1 bg-slate-900 text-white dark:bg-white dark:text-slate-900 border-none">
            Question {currentIndex + 1} of {sessionData.question_ids.length}
          </Badge>
        </div>
      </header>

      {/* Main Question Card (Made wider and cleaner) */}
    <Card className="w-full bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 shadow-sm rounded-2xl overflow-hidden">
        {/* ... Keep the CardHeader and everything inside exactly as it is ... */}
      <CardHeader className="space-y-2">
        {question?.subject && <Badge className="w-fit bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-950 dark:text-emerald-400 dark:border-emerald-800">{question.subject}</Badge>}
        <CardTitle className="text-lg font-normal leading-relaxed text-slate-900 dark:text-slate-100 pt-2">
          {question?.question}
        </CardTitle>
      </CardHeader>

      <CardContent className="space-y-3">
        {options.map((optText, idx) => {
          const optionNumber = idx
          const isSelected = selectedOption === optionNumber
          const isStruck = struckOptions.includes(optionNumber)

          let buttonStyle = 'border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/60 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/80'

          if (attemptResult) {
            if (optionNumber === attemptResult.correct_option) {
              buttonStyle = 'border-emerald-500 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-200 ring-1 ring-emerald-500'
            } else if (isSelected && !attemptResult.is_correct) {
              buttonStyle = 'border-red-500 bg-red-50 text-red-800 dark:bg-red-950/40 dark:text-red-200 ring-1 ring-red-500'
            } else {
              buttonStyle = 'border-slate-200 dark:border-slate-800 bg-slate-100 dark:bg-slate-950/40 text-slate-400 dark:text-slate-500 opacity-60'
            }
          } else if (isSelected) {
            buttonStyle = 'border-blue-500 bg-blue-50 text-blue-800 dark:bg-blue-950/30 dark:text-blue-200 ring-1 ring-blue-500'
          }

          return (
            <button
              key={optionNumber}
              type="button"
              onClick={() => handleSelectOption(optionNumber)}
              onContextMenu={(e) => handleToggleStrike(e, optionNumber)}
              disabled={Boolean(attemptResult)}
              className={`w-full text-left p-4 rounded-lg border transition-all flex items-start space-x-3 cursor-pointer select-none ${buttonStyle} ${
                isStruck && !attemptResult ? 'line-through opacity-40 text-slate-400 dark:text-slate-600' : ''
              }`}
            >
              <span className="font-semibold text-xs tracking-wider uppercase mt-0.5 opacity-70">
                {String.fromCharCode(65 + idx)}.
              </span>
              <span className="flex-1 text-sm leading-relaxed">{optText}</span>
            </button>
          )
        })}
      </CardContent>

      <CardFooter className="flex justify-end border-t border-slate-100 dark:border-slate-800/80 pt-4">
          {!attemptResult ? (
            <Button onClick={handleSubmit} disabled={selectedOption === null || attemptMutation.isPending} className="bg-emerald-600 hover:bg-emerald-500 text-white">
              {attemptMutation.isPending ? 'Checking...' : 'Submit Answer'}
            </Button>
          ) : (
            <Button onClick={handleNext} className="bg-blue-600 hover:bg-blue-500 text-white">
              {currentIndex + 1 >= sessionData.question_ids.length ? 'Finish Session' : 'Next Question →'}
            </Button>
          )}
        </CardFooter>
      </Card>

      {attemptResult && (
        <Card className="w-full bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200">
          <CardHeader>
            <div className="flex items-center space-x-2">
              <span className={`text-sm font-semibold px-2.5 py-1 rounded ${attemptResult.is_correct ? 'bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-950 dark:text-emerald-400 dark:border-emerald-800' : 'bg-red-100 text-red-800 border-red-200 dark:bg-red-950 dark:text-red-400 dark:border-red-800'}`}>
                {attemptResult.is_correct ? 'Correct' : 'Incorrect'}
              </span>
              <span className="text-sm text-slate-500 dark:text-slate-400">
                Correct choice was ({String.fromCharCode(65 + attemptResult.correct_option)})
              </span>
            </div>
          </CardHeader>
          <CardContent>
            {question?.explanation ? (
              <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-400 whitespace-pre-wrap">
                {question.explanation}
              </p>
            ) : (
              <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-100 dark:border-slate-700/50 space-y-1">
                <p className="text-sm font-medium text-slate-700 dark:text-slate-300">
                  Correct Answer: {String.fromCharCode(65 + attemptResult.correct_option)} {question?.correct_text ? `— ${question.correct_text}` : ''}
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-500">
                  This official dataset does not provide extended rationales.
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  )
}